export default {
  QUOTABLE_API: import.meta.env.VITE_QUOTABLE_API,
  IPGEOLOCATION_API: import.meta.env.VITE_IPGEOLOCATION_API,
  IPGEOLOCATION_TOKEN: import.meta.env.VITE_IPGEOLOCATION_TOKEN,
  OPENWEATHERMAP_API: import.meta.env.VITE_OPENWEATHERMAP_API,
  OPENWEATHERMAP_TOKEN: import.meta.env.VITE_OPENWEATHERMAP_TOKEN,
}
